FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY . /app

RUN uv sync --all-packages --all-groups

CMD ["sh", "-c", "uv run --directory packages/db alembic upgrade head && uv run pytest api/tests -svv"]
